# Generated by Django 3.2.13 on 2022-04-24 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logi', '0003_auto_20220424_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tank',
            name='gravel',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='tank',
            name='wallpaper',
            field=models.FileField(upload_to=''),
        ),
    ]
