# Generated by Django 3.2.13 on 2022-04-24 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logi', '0004_auto_20220424_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='tank',
            name='tank_name',
            field=models.CharField(default='hello', max_length=15),
            preserve_default=False,
        ),
    ]
