# Generated by Django 3.2.13 on 2022-04-24 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logi', '0005_tank_tank_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tank',
            name='gravel',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tank',
            name='wallpaper',
            field=models.CharField(max_length=100),
        ),
    ]
