# Generated by Django 3.2.13 on 2022-04-24 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logi', '0007_auto_20220424_2024'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='tank',
            name='gravel',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='tank',
            name='wallpaper',
            field=models.CharField(max_length=15),
        ),
    ]
