# Generated by Django 3.2.13 on 2022-04-24 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logi', '0008_auto_20220424_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='assets',
            name='name',
            field=models.CharField(default='one', max_length=15),
            preserve_default=False,
        ),
    ]
