# Generated by Django 3.2.13 on 2022-04-28 21:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('logi', '0009_assets_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Assets',
        ),
        migrations.RemoveField(
            model_name='tank',
            name='tank_name',
        ),
        migrations.AddField(
            model_name='fish',
            name='birth_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fish',
            name='idnum',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fish',
            name='imageCountX',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fish',
            name='speed',
            field=models.FloatField(default=100),
        ),
        migrations.AddField(
            model_name='fish',
            name='texturePartHeight',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='fish',
            name='texturePartWidth',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='fish',
            name='xPos',
            field=models.FloatField(default=400),
        ),
        migrations.AddField(
            model_name='fish',
            name='yPos',
            field=models.FloatField(default=400),
        ),
        migrations.AddField(
            model_name='tank',
            name='fishText',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='logi.fish'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tank',
            name='numberOfDecorations',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tank',
            name='numberOfFish',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tank',
            name='tankID',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
