# Generated by Django 3.2.13 on 2022-04-28 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logi', '0013_remove_tank_fishtext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fish',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
