# Generated by Django 3.2.13 on 2022-04-28 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logi', '0014_alter_fish_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='fish',
            name='fishLoc',
            field=models.CharField(default='no location', max_length=15),
        ),
    ]
