# Generated by Django 3.2.13 on 2022-04-28 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logi', '0015_fish_fishloc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tank',
            name='tankID',
        ),
        migrations.AddField(
            model_name='tank',
            name='tankLoc',
            field=models.CharField(default='no location', max_length=15),
        ),
    ]
