# Generated by Django 4.0.4 on 2022-04-29 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logi', '0017_fish_fishpng'),
    ]

    operations = [
        migrations.AddField(
            model_name='fish',
            name='imageCountY',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
