# Generated by Django 3.2.13 on 2022-05-05 07:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('logi', '0019_fish_sclaeheight_fish_sclaewidth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfiles',
            name='id',
        ),
        migrations.AddField(
            model_name='userfiles',
            name='tokenID',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
